// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZkufR2EzlLm87yPlzQL8IfWlfZsg_sBY',
    appId: '1:163026253937:web:c346f327af630a065c03d0',
    messagingSenderId: '163026253937',
    projectId: 'fir-authentication-e5a0a',
    authDomain: 'fir-authentication-e5a0a.firebaseapp.com',
    storageBucket: 'fir-authentication-e5a0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbH_YOkV09NOjgVOA46viqg0qL4lW5if8',
    appId: '1:163026253937:android:68a99b1fa2a116cc5c03d0',
    messagingSenderId: '163026253937',
    projectId: 'fir-authentication-e5a0a',
    storageBucket: 'fir-authentication-e5a0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl8_Llw3V61xell5p6nSgRLM96ZLuMXzA',
    appId: '1:163026253937:ios:d882d32894a5a07a5c03d0',
    messagingSenderId: '163026253937',
    projectId: 'fir-authentication-e5a0a',
    storageBucket: 'fir-authentication-e5a0a.firebasestorage.app',
    androidClientId: '163026253937-vq1s7bp3kf7il94666b06f3i6beshlej.apps.googleusercontent.com',
    iosClientId: '163026253937-igq80i9aa49i6mi2d7mnbon5q6cggv1v.apps.googleusercontent.com',
    iosBundleId: 'com.englesoft.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl8_Llw3V61xell5p6nSgRLM96ZLuMXzA',
    appId: '1:163026253937:ios:d882d32894a5a07a5c03d0',
    messagingSenderId: '163026253937',
    projectId: 'fir-authentication-e5a0a',
    storageBucket: 'fir-authentication-e5a0a.firebasestorage.app',
    androidClientId: '163026253937-vq1s7bp3kf7il94666b06f3i6beshlej.apps.googleusercontent.com',
    iosClientId: '163026253937-igq80i9aa49i6mi2d7mnbon5q6cggv1v.apps.googleusercontent.com',
    iosBundleId: 'com.englesoft.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZkufR2EzlLm87yPlzQL8IfWlfZsg_sBY',
    appId: '1:163026253937:web:df93ce59df2c4d5b5c03d0',
    messagingSenderId: '163026253937',
    projectId: 'fir-authentication-e5a0a',
    authDomain: 'fir-authentication-e5a0a.firebaseapp.com',
    storageBucket: 'fir-authentication-e5a0a.firebasestorage.app',
  );
}
